### ISSUE TITLE
Should this work with Python 3.7 on Windows 10?

### ISSUE THREAD

**Issue by dwadler** [avryhof/ambient_api#6]
I just installed this with pip but it fails trying to import AmbientAPI.

This is the complete code:
`from ambient_api import AmbientAPI

api = AmbientAPI()

devices = api.get_devices()
print (devices)
device = devices[0]

print(device.get_data())`

This is the result:
E:\dwacode\smarthome\ambientweather>python test1.py
Traceback (most recent call last):
  File "test1.py", line 2, in <module>
    from ambient_api import AmbientAPI
ImportError: cannot import name 'AmbientAPI' from 'ambient_api' (d:\python37\lib\site-packages\ambient_api\__init__.py)

E:\dwacode\smarthome\ambientweather>pip list
Package        Version
-------------- ----------
ambient-api    1.5.2

**Comment by dwadler** [comment]
Never mind. I hacked around this.

**Comment by arlenarlenarlen** [comment]
@dwadler what was your hack? I'm having the same issue on Ubuntu.

**Comment by dwadler** [comment]
I copied ambientapi.py to the directory with my source.. It would be nice to know how to fix the problem so that it works as expected.

**Comment by avryhof** [comment]
No hack needed.

Instead of 
```
from ambient_api import AmbientAPI
```

use
```
from ambient_api.ambientapi import AmbientAPI
```

I'll add it to the README

**Comment by dwadler** [comment]
Thank you. Python 'from' and 'import' are still a mystery to me.
